In [2]:
import tensorflow as tf
import pandas as pd

In [3]:
filePath = 'https://raw.githubusercontent.com/HyunjunKim1/Opentutorial_Deeplearning/main/iris.csv'
Iris = pd.read_csv(filePath)
Iris.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [4]:
# 원핫 인코딩
Iris = pd.get_dummies(Iris)

In [5]:
# 독립변수와 종속변수
independent = Iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
dependent = Iris[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(independent.shape, dependent.shape)

(150, 4) (150, 3)


In [7]:
# 모델 구조 만들기 
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [9]:
# 모델 학습시키기
model.fit(independent, dependent, epochs=1000, verbose=0)
model.fit(independent, dependent, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1535 - accuracy: 0.9867
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1531 - accuracy: 0.9867
Epoch 3/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1538 - accuracy: 0.9867
Epoch 4/10
5/5 [==============================] - 0s 3ms/step - loss: 0.1535 - accuracy: 0.9867
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1531 - accuracy: 0.9800
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1529 - accuracy: 0.9800
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1530 - accuracy: 0.9867
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1528 - accuracy: 0.9867
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1526 - accuracy: 0.9800
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1521 - accuracy: 0.9867


In [12]:
# 학습시킨 모델에 독립변수 넣어서 확인하기. 
print(model.predict(independent[:5]))
# 이후 종속변수 처음 5개가 위에서 확인해본 setosa가 맞는지 확인
print(dependent[:5])

# 처음 5개가 아니라 마지막 5개 확인하기.
print(model.predict(independent[-5:]))
print(dependent[-5:])

1/1 [==============================] - 0s 16ms/step
[[9.99184191e-01 8.15754116e-04 2.75195049e-08]
 [9.95398343e-01 4.60128160e-03 3.75410963e-07]
 [9.98475254e-01 1.52466435e-03 1.08839245e-07]
 [9.96117830e-01 3.88160092e-03 5.53396603e-07]
 [9.99453366e-01 5.46668191e-04 1.91732106e-08]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
1/1 [==============================] - 0s 18ms/step
[[1.7192601e-06 1.6415207e-01 8.3584625e-01]
 [1.8694473e-06 2.1502309e-01 7.8497499e-01]
 [5.3346635e-06 2.4791569e-01 7.5207901e-01]
 [2.5248437e-06 8.6283088e-02 9.1371441e-01]
 [1.2379764e-05 2.1899515e-01 7.8099245e-01]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
1

In [13]:
# 가중치 출력해서 확인해보기!
print(model.get_weights())

[array([[ 0.17341834,  0.5575995 , -0.98182017],
       [ 3.4459207 , -0.17529726, -1.3258268 ],
       [-3.9597642 , -0.89409626,  1.2195755 ],
       [-3.4049065 , -1.2609072 ,  1.4917015 ]], dtype=float32), array([ 1.8619981 ,  0.74562013, -1.1831207 ], dtype=float32)]
